config/routes.rb
Todo::Application.routes.draw do
  root :to => "sessions#new"

  get "project_memberships/create"
  get "project_memberships/accept_join"
  #delete "users/destroy"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  delete "log_out" => "sessions#destroy", :as => "log_out"

  root :to => "sessions#new"
 
  resources :sessions, :only => [:new, :create, :destroy]

	resources :projects do
    resources :users
    resources :tasks
    resources :project_memberships
  end

  resources :tasks do
    resources :projects
    resources :comments, :only => [:create]
  end

  resources :users do
    resources :projects
    resources :comments
  end


  #match '/auth/:provider/callback', :to => 'sessions#callback'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation
	has_secure_password

	has_many :project_memberships, :dependent => :destroy
	#has_many :accepted_memberships, :class_name => "Membership", :conditions => {:accepted => true }
	has_many :projects, :through => :project_memberships
	#has_many :accepted_projects, :through => :project_memberships, :source => :project, :conditions => {:project_memberships => {:state => {:accepted => true} }}
	has_many :comments

	validates :email, :presence => true, :uniqueness => true,
										:format => {:with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }

							
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #set_current_user @user
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        # format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    reset_session

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
	
<%= render 'form' %>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>

	<article class="acceptedProjects">
		<h3>My Projects</h3>
		<% @user.project_memberships.accepted.each do |m| %>
    		<b><%= m.project.name %></b><br />
    	<% end %>
 	</article>

 	<article class="pendingProjects">
		<h3>Pending Projects</h3>
		<% @user.project_memberships.pending_joins.each do |m| %>
   	 		<b><%= m.project.name %></b><br />
    	<% end %>
	</article>
	
	<%= link_to "New Project", new_project_path %>


	<article class="delete">
		<td><%= link_to 'Delete me', @user, confirm: 'Just do it!', method: :delete %></td>
	</article>

<% else %>
	<p> <%= @user.email %> </p>
<% end %>