config/routes.rb
Todo::Application.routes.draw do
  root :to => "sessions#new"

  get "project_memberships/create"
  get "project_memberships/accept_join"
  #delete "users/destroy"
  
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  delete "log_out" => "sessions#destroy", :as => "log_out"

  root :to => "sessions#new"
 
  resources :sessions, :only => [:new, :create, :destroy]

	resources :projects do
    resources :users
    resources :tasks
    resources :project_memberships
  end

  resources :tasks do
    resources :projects
    resources :comments, :only => [:create]
  end

  resources :users do
    resources :projects
    resources :comments
  end


  #match '/auth/:provider/callback', :to => 'sessions#callback'

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, :presence => true, :length => { :maximum => 30 }

	has_many :project_memberships, :dependent => :destroy
	has_many :users, :through => :project_memberships
	has_many :tasks, :dependent => :destroy
	#has_many :comments, :through => :task

	before_create :accept_all_project_memberships

	searchable do
		text :name
	end

	def has_user?(user)
		@project_membership = project_memberships.where(:user_id => user.id, :accepted => true)
		return @project_membership.any? 	
	end

	def false_user?(user)
		@project_membership = project_memberships.where(:user_id => user.id, :accepted => false)
		return @project_membership.any? 	
	end

	def accept_all_project_memberships
		project_memberships.map {|pm| pm.accepted = true; }
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @search = Project.search do
      fulltext params[:search]
    end
    @projects = @search.results
   #@projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

	def new
    @project = Project.new()
  end

	def create
    respond_to do |format|
      if @project = current_user.projects.create(params[:project])

        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

	def show
    @project = Project.find(params[:id])
    @task = Task.new( :project => @project )
    # @news = {
    #           :new_comments => @project.tasks.map(&:comments).map(&:new_comments),
    #            :newly_completed_tasks => @project.tasks.map(&:newly_completed),
    #            :newly_added_tasks => @project.tasks.map(&:newly_added_tasks)
    #         }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<% end %>

app/views/projects/index.html.erb
<%= form_tag projects_path, :method => :get do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p> 
<% end %>

<% @projects.each do |project| %>
  <article>
    <div class="projects">
    	<strong><%= link_to project.name, project_path(project) %></strong> 
   	</div>
  </article>
<% end %>

app/views/projects/new.html.erb
<% if current_user %>

<h1>New project</h1>


<%= render 'form' %>

<% end %>

app/views/projects/show.html.erb
<h1 id="projectName"><%= @project.name %></h1>

<p id="notice"><%= notice %></p>

<% if !@project.has_user?(current_user) %>
<% if !@project.false_user?(current_user)%>
  <%= link_to 'Join', :controller => "project_memberships", :action => "create", :id => @project %>
<% end %> 
<% end %> 


<% if @project.has_user?(current_user) %>
	<div id="task-field">
  		<%= render :partial => 'tasks/form' %>
	</div>
<% end %> 

<article id="taskComment">
  <% @project.tasks.each do |task| %>
    <div class="task">
			<b><%= task.name %></b>
   			<% task.comments.each do |c| %>
          <div class="comment">
   				  <p><%= c.body %></p>		
   			  <% end %>
   		  </div>
  </div>
  <% if @project.has_user?(current_user) %>
   	<div id="comment-field">
  		<%= render :partial => "comments/form", :locals => {:task => task, :comment => task.comments.build} %>
  	</div>
  <% end %>
<% end %>
</article>

<p>users working on this project:</p>
<% @project.project_memberships.accepted.each do |m| %>
  <p>
    <b><%= m.user.email %></b><br />
  </p>
<% end %>

<article id="news">
  <p id="projectNews">Project News</p>
  <% @project.tasks.newly_added_tasks.each do |t| %>
    <p>added task: <%= t.name %></p>    
  <% end %>

  <% @project.tasks.each do |task| %>
        <% task.comments.new_comments.each do |c| %>
          <div class="comment">
            <p>added comments: <%= c.body %></p>    
          <% end %>
        </div>
  </div>
<% end %>
</article>



<% if @project.has_user?(current_user) %>
  <% ProjectMembership.pending_joins.each do |pm| %>
    <% if pm.user_id != current_user.id %>
      <% user = User.find(pm.user_id) %>
      <p><%= link_to "Accept " << user.email, :controller => "project_memberships", :action => "accept_join", :id => pm.id %></p> 
    <% end %>
  <% end %>
<% end %> 
</article>

<article id="taskLatestComment">
  <% @project.tasks.each do |task| %>
        <% task.comments.new_comments.each do |c| %>
          <div class="comment">
            <p><%= c.body %></p>    
          <% end %>
        </div>
  </div>
<% end %>
</article>